services:

  db:
    image: 'postgres:16.2'
    container_name: trade-organization-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: trade-organization
      POSTGRES_USER: trade-organization-owner
      POSTGRES_PASSWORD: trade-organization-owner

  migrate:
    image: migrate/migrate
    container_name: trade-organization-migrate
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://trade-organization-owner:trade-organization-owner@trade-organization-db:5432/trade-organization?sslmode=disable", "up"]
    depends_on:
      - db