services:

  db:
    image: 'postgres:16.2'
    container_name: trade-organization-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: trade-organization
      POSTGRES_USER: trade-organization-owner
      POSTGRES_PASSWORD: trade-organization-owner
